---
- name: Install essential packages for the build
  hosts: boxes
  become: true
  vars_files:
    - ../host_vars/boxes.yml
  tasks:
    - include_tasks: ../tasks/main.yml
  handlers:
    - name: Reload Apache
      ansible.builtin.service:
        name: apache2
        state: reloaded
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
  