#!/bin/bash

# Ensure location at VAGRANT_DIR
if [ "$PWD" != "$VAGRANT_DIR" ]; then
    cd "$VAGRANT_DIR"
fi

ANSIBLE_PUB_KEY="$HOME/.ssh/ansible_key.pub"
VAGRANT_PRIV_KEY="$VAGRANT_DIR/.vagrant/machines/*/virtualbox/private_key"
VAGRANT_NUM_VM_RUNNING="`vagrant status | grep "running" | wc -l`"
VAGRANT_NUM_VM_TOTAL="`vagrant status | grep "virtualbox" | wc -l`"
VAGRANT_VM_NAME=`vagrant status | grep 'running' | cut -d ' ' -f1`

# Load ssh-agent() function
source $VAGRANT_DIR/Scripts/ssh_agent.sh

# Adds private keys generated by vagrant to the authentication agent
for vm_path in $(ls $VAGRANT_PRIV_KEY); do ssh-add $vm_path; done

# Output number of running vm's
if [ $VAGRANT_NUM_VM_TOTAL = $VAGRANT_NUM_VM_RUNNING ]; then
    echo "Number of running vms is: $VAGRANT_NUM_VM_RUNNING"
else
    echo -e "These VM's aren't running:"'\n'"$(vagrant status | awk 'NR>2&&NR<5' |grep -v running)"
fi

# ssh-copy-id ~/.ssh/ansible_key.pub to each vm
for i in $VAGRANT_VM_NAME; do ssh-copy-id -i $ANSIBLE_PUB_KEY vagrant@$i; done
